-- Skinlu product seed.
-- Run after supabase/schema.sql.
-- image_url and price_eur are intentionally null: do not invent commercial data.
-- Affiliate links use the requested Amazon tag: skinlu-21.
-- Rows without a verified Amazon.fr ASIN use an Amazon.fr search URL fallback.

insert into products (
  name,
  brand,
  concerns,
  skin_types,
  product_type,
  routine_step,
  step_order,
  affiliate_url,
  image_url,
  price_eur
) values
  (
    'Hydrating Cleanser',
    'CeraVe',
    array['dehydration', 'sensitivity'],
    array['dry', 'sensitive', 'normal'],
    'cleanser',
    'both',
    10,
    'https://www.amazon.fr/dp/B00D7BZJ3C?tag=skinlu-21',
    null,
    null
  ),
  (
    'Effaclar Gel Purifiant',
    'La Roche-Posay',
    array['acne', 'enlarged_pores'],
    array['oily', 'combination', 'sensitive'],
    'cleanser',
    'both',
    10,
    'https://www.amazon.fr/dp/B003JSEGNC?tag=skinlu-21',
    null,
    null
  ),
  (
    'Sensibio H2O',
    'Bioderma',
    array['sensitivity', 'dehydration'],
    array['sensitive', 'dry', 'normal'],
    'cleanser',
    'both',
    10,
    'https://www.amazon.fr/dp/B002XZLAWM?tag=skinlu-21',
    null,
    null
  ),
  (
    'Cleanance Gel Nettoyant',
    'Avene',
    array['acne', 'enlarged_pores'],
    array['oily', 'combination', 'sensitive'],
    'cleanser',
    'both',
    10,
    'https://www.amazon.fr/dp/B08JGPSWTZ?tag=skinlu-21',
    null,
    null
  ),
  (
    'Huile Nettoyante',
    'Typology',
    array['dehydration', 'sensitivity', 'dullness'],
    array['dry', 'normal', 'combination', 'sensitive'],
    'cleanser',
    'evening',
    10,
    'https://www.amazon.fr/s?k=Typology+Huile+Nettoyante&tag=skinlu-21',
    null,
    null
  ),
  (
    'Essence Toner',
    'Pyunkang Yul',
    array['dehydration', 'sensitivity'],
    array['dry', 'sensitive', 'normal', 'combination'],
    'toner',
    'both',
    20,
    'https://www.amazon.fr/dp/B06ZZK3YJY?tag=skinlu-21',
    null,
    null
  ),
  (
    'AHA BHA PHA 30 Days Miracle Toner',
    'Some By Mi',
    array['acne', 'enlarged_pores', 'dullness'],
    array['oily', 'combination'],
    'toner',
    'evening',
    20,
    'https://www.amazon.fr/dp/B09Z6JRY3Y?tag=skinlu-21',
    null,
    null
  ),
  (
    'Supple Preparation Toner Unscented',
    'Klairs',
    array['dehydration', 'sensitivity', 'dullness'],
    array['dry', 'sensitive', 'normal', 'combination'],
    'toner',
    'both',
    20,
    'https://www.amazon.fr/dp/B075MZPH82?tag=skinlu-21',
    null,
    null
  ),
  (
    'Hyaluronic Acid 2% + B5',
    'The Ordinary',
    array['dehydration', 'dullness'],
    array['dry', 'normal', 'combination', 'oily', 'sensitive'],
    'serum',
    'both',
    30,
    'https://www.amazon.fr/dp/B01MYEZPC8?tag=skinlu-21',
    null,
    null
  ),
  (
    'Niacinamide 10% + Zinc 1%',
    'The Ordinary',
    array['acne', 'enlarged_pores', 'dullness'],
    array['oily', 'combination', 'normal'],
    'serum',
    'both',
    30,
    'https://www.amazon.fr/dp/B01MDTVZTZ?tag=skinlu-21',
    null,
    null
  ),
  (
    'Retinol B3 Serum',
    'La Roche-Posay',
    array['aging', 'dark_spots', 'dullness'],
    array['normal', 'dry', 'combination'],
    'serum',
    'evening',
    30,
    'https://www.amazon.fr/dp/B07Z9Y4M3C?tag=skinlu-21',
    null,
    null
  ),
  (
    '2% BHA Liquid Exfoliant',
    'Paula''s Choice',
    array['acne', 'enlarged_pores', 'dullness'],
    array['oily', 'combination', 'normal'],
    'serum',
    'evening',
    30,
    'https://www.amazon.fr/dp/B00949CTQQ?tag=skinlu-21',
    null,
    null
  ),
  (
    'Serum Vitamine C 10%',
    'Typology',
    array['dark_spots', 'dullness', 'aging'],
    array['normal', 'combination', 'oily'],
    'serum',
    'morning',
    30,
    'https://www.amazon.fr/s?k=Typology+Serum+Vitamine+C+10&tag=skinlu-21',
    null,
    null
  ),
  (
    '10 Ingredients Serum',
    'Typology',
    array['dehydration', 'sensitivity'],
    array['dry', 'sensitive', 'normal', 'combination'],
    'serum',
    'both',
    30,
    'https://www.amazon.fr/s?k=Typology+10+Ingredients+Serum&tag=skinlu-21',
    null,
    null
  ),
  (
    'Crystal Retinal 3',
    'Medik8',
    array['aging', 'dark_spots', 'dullness'],
    array['normal', 'dry', 'combination'],
    'serum',
    'evening',
    30,
    'https://www.amazon.fr/s?k=Medik8+Crystal+Retinal+3&tag=skinlu-21',
    null,
    null
  ),
  (
    'Lactic Acid 10% + HA',
    'The Ordinary',
    array['dullness', 'dark_spots', 'enlarged_pores'],
    array['normal', 'dry', 'combination'],
    'serum',
    'evening',
    30,
    'https://www.amazon.fr/dp/B07NDNPCKW?tag=skinlu-21',
    null,
    null
  ),
  (
    'Moisturizing Cream',
    'CeraVe',
    array['dehydration', 'sensitivity'],
    array['dry', 'sensitive', 'normal'],
    'moisturizer',
    'both',
    40,
    'https://www.amazon.fr/dp/B0853C7CFQ?tag=skinlu-21',
    null,
    null
  ),
  (
    'Effaclar Mat',
    'La Roche-Posay',
    array['acne', 'enlarged_pores'],
    array['oily', 'combination'],
    'moisturizer',
    'both',
    40,
    'https://www.amazon.fr/dp/B00EKDV674?tag=skinlu-21',
    null,
    null
  ),
  (
    'Hydrance Optimale Legere',
    'Avene',
    array['dehydration', 'sensitivity'],
    array['normal', 'combination', 'sensitive'],
    'moisturizer',
    'both',
    40,
    'https://www.amazon.fr/s?k=Avene+Hydrance+Optimale+Legere&tag=skinlu-21',
    null,
    null
  ),
  (
    'Hydro Boost Water Gel',
    'Neutrogena',
    array['dehydration', 'dullness'],
    array['normal', 'combination', 'oily'],
    'moisturizer',
    'both',
    40,
    'https://www.amazon.fr/s?k=Neutrogena+Hydro+Boost+Water+Gel&tag=skinlu-21',
    null,
    null
  ),
  (
    'Cicaplast Baume B5+',
    'La Roche-Posay',
    array['sensitivity', 'dehydration'],
    array['dry', 'sensitive', 'normal'],
    'moisturizer',
    'both',
    40,
    'https://www.amazon.fr/dp/B0060OUV5Y?tag=skinlu-21',
    null,
    null
  ),
  (
    'Creme Riche Reparatrice',
    'Typology',
    array['dehydration', 'sensitivity'],
    array['dry', 'sensitive'],
    'moisturizer',
    'both',
    40,
    'https://www.amazon.fr/s?k=Typology+Creme+Riche+Reparatrice&tag=skinlu-21',
    null,
    null
  ),
  (
    'Anthelios Invisible Fluid SPF 50+',
    'La Roche-Posay',
    array['dark_spots', 'aging', 'sensitivity'],
    array['dry', 'normal', 'combination', 'oily', 'sensitive'],
    'spf',
    'morning',
    50,
    'https://www.amazon.fr/dp/B09SLDHKTN?tag=skinlu-21',
    null,
    null
  ),
  (
    'Mineral SPF 50 Tinted',
    'CeraVe',
    array['dark_spots', 'sensitivity'],
    array['dry', 'normal', 'combination', 'sensitive'],
    'spf',
    'morning',
    50,
    'https://www.amazon.fr/s?k=CeraVe+Mineral+SPF+50+Tinted&tag=skinlu-21',
    null,
    null
  ),
  (
    'Cleanance Solaire SPF 50+',
    'Avene',
    array['acne', 'dark_spots', 'enlarged_pores'],
    array['oily', 'combination', 'sensitive'],
    'spf',
    'morning',
    50,
    'https://www.amazon.fr/s?k=Avene+Cleanance+Solaire+SPF+50&tag=skinlu-21',
    null,
    null
  ),
  (
    'SPF 50 Quotidien',
    'Typology',
    array['dark_spots', 'aging', 'dullness'],
    array['normal', 'combination', 'dry'],
    'spf',
    'morning',
    50,
    'https://www.amazon.fr/s?k=Typology+SPF+50+Quotidien&tag=skinlu-21',
    null,
    null
  ),
  (
    'Caffeine Eye Cream',
    'The INKEY List',
    array['dullness', 'aging'],
    array['dry', 'normal', 'combination', 'oily'],
    'serum',
    'both',
    35,
    'https://www.amazon.fr/dp/B07GLNN427?tag=skinlu-21',
    null,
    null
  ),
  (
    'Pigmentclar Yeux',
    'La Roche-Posay',
    array['dark_spots', 'dullness', 'aging'],
    array['dry', 'normal', 'combination', 'sensitive'],
    'serum',
    'both',
    35,
    'https://www.amazon.fr/s?k=La+Roche-Posay+Pigmentclar+Yeux&tag=skinlu-21',
    null,
    null
  );
